### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by somedevreally** [pictuga/morss#73] opened 2021-12-12 20:39 UTC
got new docker error,

```
Traceback (most recent call last):
  File "/usr/bin/gunicorn", line 5, in <module>
    from gunicorn.app.wsgiapp import run
  File "/usr/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "/usr/lib/python3.9/site-packages/gunicorn/app/base.py", line 11, in <module>
    from gunicorn import util
  File "/usr/lib/python3.9/site-packages/gunicorn/util.py", line 25, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

thanks

**Comment by pictuga** [comment] 2021-12-12 21:13
Should be fixed in def397de5e (docker build in progress). Thanks again for reporting! Feel free to reopen if the issue isn't fixed.

**Closed by pictuga** 2021-12-12 21:13 UTC
