### ISSUE TITLE
Error morss-helper: python not found

### ISSUE THREAD

**Issue by aberlaas** [pictuga/morss#79] opened 2021-12-28 16:43 UTC
Hi,

Thank you for the hard work :)

Docker container is not running anymore. I think it may be related to your last commit.

Here the error code sent by the container:
```
/app/morss-helper: line 34: python: not found
```

Thanks,

**Comment by pictuga** [comment] 2021-12-29 13:09
Should be fixed by 676be4a4fed0020a3a7dce95a1fdbe3520b5839b

**Comment by pictuga** [comment] 2021-12-29 15:10
Should both be fixed as of ecdb74812dc3e96188b4d70b5b034622ea934246 (published to docker hub just now)

**Comment by oliroe** [comment] 2021-12-29 15:50
Thanks, now it's starts fine
Doubt it's related to this but Portainer reports the container as unhealthy but gives no help on what the issue is

![image](https://user-images.githubusercontent.com/4500141/147679747-74ef115d-d4bf-415a-938b-ea982d5636fc.png)

**Comment by pictuga** [comment] 2021-12-29 17:03
Good to see it's all solved

**Closed by pictuga** 2021-12-29 17:03 UTC
